export const BACKEND_URL = "http://192.168.113.3:9000/api/game-info";
export const GAMENAMES = {
  GOD_OF_FORTUNE: "God Of Fortune",
  WILD_WEST_SALOON: "Wild West Saloon",
  SAKURA_NEKO: "Sakura Neko",
  SUGARY_BONANZA: "Sugary Bonanza",
  PERSIAN_GEMS: "Persian Gems",
  QUEEN_OF_AZTEC: "Queen of Aztec",
  STALLION_PRINCESS: "Stallion Princess",
  MAHJONG_FORTUNE: "Mahjong Fortune",
  GATES_OF_KUNLUN: "Gates of Kunlun",
  SANGUO: "SanGuo - The Brotherhood",
  MERMAID_TREASURE: "Mermaid's Treasure",
  LONGEVITY_DRAGON: "Longevity dragon",
  MYSTERIES_OF_PANDORA: "Mysteries of Pandora",
  STEAMPUNK_RELOADED: "Steampunk Reloaded",
  LEGENDARY_EL_TORO: "Legendary El Toro",
  KAWAII_NEKO: "Kawaii Neko",
  BIKINI_BABES: "Bikini Babes",
  SEXY_CHRISTMAS_SIRENS: "Sexy Christmas Sirens",
  SPRING_HARVEST: "Spring Harvest",
  AMAZING_CIRCUS: "Amazing Circus",
  APHRODITE: "Aphrodite - Goddess of Love",
  SUPER_PHOENIX: "Super Phoenix",
  CHASING_LEPRECHAUN_COINS: "Chasing Leprechaun Coins",
  TEMPLE_OF_GODS: "Temple Of Gods",
  MOCHI_MOCHI: "Mochi Mochi",
};
